# The key id of a gpg key in the "gpg subdirectory goes here
# You can use the "make gpg-key" helper to create that if you
# full out KEY_USER below
#RELEASE_GPG_KEY=<your gpg key>

# This is the gpg key user id that 'make gpg-key' uses for the gpg key
# If you chose to use that to create a gpg id
#KEY_USER=<your@email.com>

# The url of your public repository which is embedded in the generated
# .flatpakref file
#URL=http://url/to/your/public/repository
